### PR TITLE
Update german.json

### PR DESCRIPTION
**Pull request by FirstDeltaa**
Letters (ä, ö, ü in caps)
Some changes due to the field size
Some translation mistakes

### CODE REVIEW

**Comment by m0uka** [comment]
Looks fine, but why did you make some phrases uppercase?

**Comment by FirstDeltaa** [comment]
Some words are in caps. "ä", "ö", "ü" remain small.
https://prnt.sc/u7xy5f

**Comment by FirstDeltaa** [comment]
But it would also suffice to capitalize the individual letters.

**Comment by m0uka** [comment]
Okay, approved

**Pull request merged**
